DROP DATABASE IF EXISTS auth;

CREATE DATABASE IF NOT EXISTS auth;

USE auth;

CREATE TABLE users (
	id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(30) NOT NULL,
	email VARCHAR(50) NOT NULL UNIQUE,
	password VARCHAR(1000) NOT NULL
)